---
- name: Install Apache
  become: true
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Install Git
  become: true
  ansible.builtin.yum:
    name: git
    state: present

- name: Clone the Tooling repository
  become: true
  ansible.builtin.git:
    repo: https://github.com/Captnfresh/tooling.git
    dest: /var/www/html
    force: yes

- name: Move content to parent directory
  become: true
  command: cp -r /var/www/html/html/ /var/www/

- name: Start httpd service
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: Remove redundant html directory
  become: true
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent
---
# tasks file for webserver
