---
- hosts: all
- import_playbook: ../static-assignments/common.yml

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml

import_playbook: ../static-assignments/db-servers.yml


name: todo
import_playbook: ../static-assignments/todo.yml